Login
christopherpeters-git/WebProgrammierungSoSe2020 pull request #29
Opened 2020-04-22 22:42 UTC by siIsaak

Login Funktion hinzugefügt bitte nach developer mergen.

2020-04-24 04:46 UTC, christopherpeters-git requested changes
-Text vom "Login"-Button (Aktuell "Lgoin") korrigieren
-"E-Mail Adresse" vielleicht zu nur "E-Mail" ändern?
Das grüne Design gefällt mir ziemlich gut. Was gilt als valide E-Mail im Login-Feld?

2020-04-24 10:09 UTC, tillfri reviewed
Sieht gut aus, die Funktionalität im Sinne einer echten Überprüfung der eingegeben Daten besteht allerdings noch nicht, oder habe ich etwas übersehen?

2020-04-25 18:33 UTC, siIsaak commented
-Text vom "Login"-Button korrigiert.
- "E-Mail Adresse" zu E-Mail geändert.
Die Überprüfung der Daten wird durchgeführt dadurch, dass der Input vom Type "email" und "password" ist. Dadurch überprüft der Browser automatisch ob es eine richtige E-Mail Adresse ist.
Es wird über prüft ob vor und nach dem @ etwas steht und ob es nach dem @ noch eine ".Toplevel Domain" gibt.
Ich hab in dem Zuge noch eine Kleinigkeit am Design verändert.

2020-04-25 18:36 UTC, christopherpeters-git approved these changes

2020-04-25 18:36 UTC, merged